#!/bin/sh

# Update the Android gitignore file
wget -O Android.gitignore https://raw2.github.com/github/gitignore/master/Android.gitignore
echo "Use Android.gitignore for Android projects"

GIT_IGNORE=~/.global_gitignore;
export GIT_IGNORE

mkdir -p ~/bin && 

{ cp -v git-adjust ~/bin/git-adjust ;
cp -v hg-adjust ~/bin ;
cp -v git-last-archive ~/bin ;
cp -v .global_gitignore $GIT_IGNORE ;

echo ;
git-adjust ;
hg-adjust ;
}
