#!/bin/sh

GIT_IGNORE=.global_gitignore
HG_IGNORE=.global_hgignore
USER_NAME='Maksim Dmitriev'
USER_EMAIL=maksim.a.dmitriev@gmail.com

export GIT_IGNORE
export HG_IGNORE
export USER_NAME
export USER_EMAIL

mkdir -p ~/bin && 

{ cp -v git-adjust ~/bin/git-adjust ;
cp -v hg-adjust ~/bin ;
cp -v git-last-archive ~/bin ;
cp -v $GIT_IGNORE ~/$GIT_IGNORE ;
cp -v $HG_IGNORE ~/$HG_IGNORE ;
echo ;
git-adjust ;
hg-adjust ;
}
